COGNITIVE_TRAITS_BANK= {
    "Kraepelin Test (Numerik)" : 
        "Analisis EEG menunjukkan bahwa individu ini memiliki respons elektrofisiologis yang lebih tinggi pada tugas working memory dibandingkan dengan tugas digit span dan stimulus logika. Hal ini tercermin dari peningkatan aktivitas pada frekuensi theta di area frontal selama tugas-tugas yang menuntut manipulasi informasi dalam working memory. Penelitian oleh Jensen dan Tesche (2002) menunjukkan bahwa aktivitas theta frontal meningkat seiring dengan beban kerja dalam tugas working memory, menandakan keterlibatan intensif dari sistem memori kerja."
        "<br/><br/>"
        "Keunggulan utama individu dengan dominasi working memory adalah kemampuannya dalam memanipulasi informasi sementara, yang sangat penting dalam tugas-tugas kompleks dan pengambilan keputusan. Hal ini memungkinkan individu untuk melakukan multitasking dan menyelesaikan masalah dengan lebih efisien. Namun, beban kognitif yang tinggi dapat menyebabkan kelelahan mental jika digunakan secara berlebihan tanpa istirahat yang memadai. Penelitian oleh Alloway et al. (2009) menunjukkan bahwa individu dengan kapasitas working memory rendah cenderung mengalami kesulitan dalam tugas-tugas yang menuntut perhatian berkelanjutan."
        "<br/><br/>"
        "Working memory dapat ditingkatkan melalui latihan dan praktik yang dirancang untuk meningkatkan kapasitas dan kecepatan pemrosesan informasi. Pelatihan ini tidak hanya memperkuat working memory tetapi juga mendukung perkembangan kognitif secara keseluruhan, termasuk kemampuan untuk mengatasi tugas-tugas yang membutuhkan pemikiran analitis dan kritis. Gathercole et al. (2008) menekankan pentingnya intervensi berbasis kelas untuk membantu anak-anak dengan kesulitan working memory, yang dapat meningkatkan prestasi akademik jangka panjang."
        "<br/><br/>"
        "Hasil EEG menunjukkan kecenderungan aktivitas pada hemisfer kiri, khususnya pada channel AF3, AF4, T7, dan FZ. Channel AF3 dan AF4, yang berada di area prefrontal, sering digunakan untuk menilai aktivitas yang terkait dengan working memory, terutama dalam tugas-tugas kognitif yang melibatkan manipulasi informasi. Sementara itu, channel T7 dan FZ, yang terletak di wilayah temporal dan frontal, dapat menunjukkan aktivitas numerik dan digit span, yang merupakan bagian dari evaluasi fungsi kognitif numerik dan memori jangka pendek. Penelitian oleh Onton et al. (2005) mendukung temuan ini dengan menunjukkan bahwa aktivitas EEG di area frontal meningkat seiring dengan beban kerja dalam tugas memori kerja."
        "<br/><br/>"
        "Secara keseluruhan, profil EEG individu ini menunjukkan dominasi aktivitas di area prefrontal kiri, yang berkaitan dengan kemampuan numerik tinggi. Peningkatan aktivitas theta di area frontal selama tugas working memory menunjukkan keterlibatan intensif dari sistem memori kerja. Namun, penting untuk memperhatikan beban kognitif yang tinggi dan potensi kelelahan mental yang dapat terjadi akibat penggunaan working memory yang berlebihan tanpa istirahat yang memadai. Pelatihan dan praktik yang dirancang untuk meningkatkan kapasitas working memory dapat membantu individu dalam mengatasi tugas-tugas kompleks dan meningkatkan kinerja kognitif secara keseluruhan."
    ,
    "WCST (Logika)" : 
        "Hasil tes EEG pada stimulus logika menunjukkan pola respons elektrofisiologis yang paling dominan pada area frontal dan parietal, yang berkaitan erat dengan pemrosesan informasi dan pengambilan keputusan yang lebih kompleks. Peningkatan aktivitas gelombang beta di kanal F3 dan F4 yang terletak di bagian prefrontal cortex mengindikasikan aktivitas kognitif yang tinggi saat individu melakukan tugas-tugas logika yang membutuhkan pemikiran analitis dan penyelesaian masalah. Gelombang beta ini sering dikaitkan dengan konsentrasi dan pemrosesan informasi secara mendalam dalam situasi yang memerlukan perhatian penuh (Klimesch, 1999; Pfurtscheller & Neuper, 2001). Penelitian sebelumnya menunjukkan bahwa kemampuan untuk memecahkan masalah logika dapat diprediksi melalui pola gelombang beta, yang juga berhubungan dengan kemampuan untuk bekerja secara sistematis dalam skenario yang menuntut kecepatan pengambilan keputusan (Thut et al., 2006)."
        "<br/><br/>"
        "Kelebihan utama individu yang memiliki kecenderungan logika yang tinggi adalah kemampuannya dalam melakukan pemecahan masalah dengan pendekatan yang sistematis, serta kemampuan untuk berpikir analitis secara cepat. Keunggulan ini sangat berguna dalam pengambilan keputusan yang melibatkan evaluasi kritis terhadap informasi yang tersedia dan penyelesaian masalah dengan cara yang lebih efisien. Pada tes EEG, kecenderungan ini ditunjukkan dengan peningkatan aktivitas di kanal-kanal frontal dan parietal yang relevan, seperti F3 dan P3, yang menunjukkan keterlibatan dalam evaluasi dan pemrosesan informasi kompleks (Neubauer & Fink, 2009). Selain itu, individu dengan kemampuan logika yang kuat seringkali lebih unggul dalam situasi yang memerlukan pendekatan terstruktur dan logis, seperti dalam bidang sains, matematika, atau teknologi."
        "<br/><br/>"
        "Namun, kelemahan utama dari individu dengan kecenderungan logika yang tinggi adalah kecenderungan untuk terlalu fokus pada detail dan kehilangan perspektif lebih besar yang diperlukan dalam situasi yang membutuhkan kreativitas dan fleksibilitas. Penelitian menunjukkan bahwa individu yang sangat mengutamakan pendekatan logis dapat mengalami kesulitan dalam menghadapi masalah yang memerlukan pemikiran out-of-the-box dan inovatif, karena mereka cenderung mengandalkan solusi yang sudah terbukti (Goel et al., 2000). Hal ini dapat mengurangi kemampuan mereka untuk beradaptasi dengan cepat terhadap perubahan yang tidak terduga, yang merupakan tantangan dalam lingkungan kerja yang dinamis."
        "<br/><br/>"
        "Dalam konteks pengembangan, kemampuan logika dapat ditingkatkan dengan latihan berpikir kritis dan analitis, yang mengajak individu untuk memperhatikan hubungan antar konsep dan mengembangkan solusi berdasarkan pemikiran yang terstruktur. Berbagai metode pelatihan, seperti latihan penyelesaian masalah yang berorientasi pada logika atau permainan otak yang melibatkan analisis yang mendalam, dapat membantu memperkuat jaringan otak yang terlibat dalam proses pemikiran logis. Pelatihan semacam ini telah terbukti dapat meningkatkan kemampuan untuk berpikir secara lebih sistematis dan terorganisir (O'Reilly & Frank, 2006; Gray, 2004). Dengan peningkatan kemampuan logika ini, individu tidak hanya dapat lebih efisien dalam menyelesaikan tugas yang berhubungan dengan analisis, tetapi juga dapat meningkatkan kemampuan mereka untuk bekerja dengan lebih kreatif dalam mengatasi tantangan yang lebih kompleks."
        "<br/><br/>"
        "Hasil penelitian EEG menunjukkan adanya keterlibatan dominan dari hemisfer kiri, terutama di kanal F3 dan P3, yang sering kali terkait dengan tugas-tugas yang melibatkan logika dan analisis numerik (Shin et al., 2007). Kanal-kanal ini sering digunakan untuk mengevaluasi aktivitas kognitif yang berhubungan dengan tugas-tugas berpikir kritis dan keputusan logis. Aktivitas yang ditunjukkan oleh peningkatan gelombang beta ini merupakan indikator penting bahwa otak sedang mengerjakan proses yang kompleks, termasuk evaluasi pilihan dan pengambilan keputusan berdasarkan informasi yang tersedia."

    ,
    "Digit Span (Short Term Memory)" :
        "Hasil tes EEG pada stimulus yang menguji memori jangka pendek menunjukkan pola respons elektrofisiologis yang lebih kuat pada gelombang theta dan alpha, yang berhubungan dengan pengolahan informasi jangka pendek. Aktivitas yang lebih dominan terlihat pada kanal-kanal posterior, seperti P3 dan O1, yang terletak di area temporal dan oksipital otak, yang terkait dengan pemrosesan visual dan pengingatan informasi dalam waktu singkat. Penelitian menunjukkan bahwa peningkatan aktivitas gelombang theta di area ini berhubungan dengan pengolahan dan penyimpanan informasi dalam memori jangka pendek (Klimesch, 1996; Basar et al., 2001). Aktivitas ini dapat terjadi saat individu diminta untuk mengingat serangkaian angka atau kata dalam jangka waktu yang terbatas, yang mengindikasikan keterlibatan intens dalam memori jangka pendek."
        "<br/><br/>"
        "Keunggulan utama dari individu dengan kemampuan memori jangka pendek yang tinggi adalah kemampuan untuk mengingat dan memproses informasi dalam waktu yang sangat singkat, yang sangat penting dalam berbagai situasi yang membutuhkan pengambilan keputusan cepat. Penelitian oleh Cowan (2001) menunjukkan bahwa individu dengan kapasitas memori jangka pendek yang lebih besar dapat lebih efisien dalam menyelesaikan tugas-tugas yang membutuhkan pengingatan informasi untuk waktu yang terbatas, seperti dalam percakapan cepat atau saat mengambil keputusan dalam lingkungan yang penuh informasi. Mereka cenderung memiliki kemampuan lebih untuk mengingat instruksi, angka, atau urutan informasi dengan cepat, yang memberikan keunggulan dalam situasi kerja atau pembelajaran yang melibatkan memori aktif."
        "<br/><br/>"
        "Namun, kelemahan utama individu dengan memori jangka pendek yang tinggi adalah keterbatasan dalam mengingat informasi dalam jangka waktu yang lebih lama. Penelitian menunjukkan bahwa meskipun mereka mampu menyimpan dan mengingat informasi dalam waktu singkat, mereka mungkin mengalami kesulitan dalam mempertahankan informasi tersebut dalam jangka panjang, yang berpotensi menghambat kemampuan mereka dalam situasi yang membutuhkan pengingatan informasi secara permanen (Baddeley, 2003). Hal ini dapat mempengaruhi kemampuan mereka untuk mengingat informasi yang telah dipelajari dalam konteks jangka panjang, yang menjadi penting dalam pembelajaran atau pengelolaan informasi yang lebih rumit dan memerlukan integrasi informasi."
        "<br/><br/>"
        "Dalam konteks pengembangan, kemampuan memori jangka pendek dapat ditingkatkan melalui latihan yang menstimulasi proses penyimpanan dan pengambilan informasi dalam jangka waktu singkat. Berbagai teknik pelatihan, seperti latihan ingatan berbasis urutan atau permainan otak yang melibatkan peningkatan kecepatan pengingatan, dapat membantu memperkuat kemampuan memori jangka pendek. Penelitian menunjukkan bahwa pelatihan yang melibatkan pengulangan informasi dalam waktu singkat dapat meningkatkan kapasitas memori jangka pendek (Salthouse, 1996; Jaeggi et al., 2008). Selain itu, latihan yang melibatkan pengolahan informasi dalam konteks yang lebih variatif juga dapat membantu mempercepat pemrosesan informasi dalam memori jangka pendek, sehingga individu menjadi lebih efisien dalam menyelesaikan tugas-tugas yang membutuhkan ketahanan memori."
        "<br/><br/>"
        "Hasil penelitian EEG menunjukkan bahwa kanal-kanal yang terlibat dalam memori jangka pendek, seperti P3 dan O1, berfungsi dalam konteks pengolahan informasi visual dan verbal dalam waktu yang singkat. Peningkatan aktivitas gelombang theta dan alpha di area posterior menunjukkan bahwa otak sedang bekerja untuk memanipulasi informasi yang baru saja diterima dan menyimpannya dalam memori jangka pendek (Vogel et al., 2005). Hal ini sangat penting dalam memahami bagaimana individu dengan memori jangka pendek yang kuat dapat lebih efektif dalam pengambilan keputusan cepat dan dalam situasi yang melibatkan pengingatan informasi dengan durasi singkat."
            
}